### ISSUE TITLE
Dynamic Habitat Graph

### ISSUE THREAD

**Issue by HWR-llc** [HWR-llc/ett#100]
create a new component `components/subs/HabitatGraphDynamic.vue` that includes filtering and printing capabilities.

Add button to Habitat Graph with print icon (in red?)
[https://icons.getbootstrap.com/icons/printer/](url)

<img width="315" alt="image" src="https://github.com/user-attachments/assets/033d45e9-aab7-4771-b984-cd7bd244b150">

**Comment by jcjucelyn** [comment]
basic foundation done
