### ISSUE TITLE
Clicking of Diadromous Fish Runs Has Inconsistent Behavior, Tooltip Position

### ISSUE THREAD

**Issue by HWR-llc** [HWR-llc/ett#101]
If the tooltip for a river does not come up, you cannot click on the river even though the cursor looks like you can click it:
![image](https://github.com/user-attachments/assets/1945f6dc-1376-4733-ba78-a697bdf2a1bd)

But if you tooltip is up, you can click it and update the graph
![image](https://github.com/user-attachments/assets/657b965e-bbba-4776-9352-9f13deb0aad9)

Also, noted that it looks like the tooltip appears at the geometric center of a bounding box for the river, but that point may not be on the river:
![image](https://github.com/user-attachments/assets/964ab242-b42f-4bfc-ba37-c6cbc4994865)
Not sure what the fix is here, but thinking it should be to have the tooltip show next to the cursor (if possible).

**Comment by jcjucelyn** [comment]
tooltip now follows the mouse
