### ISSUE TITLE
Better Integration of Data Filtering

### ISSUE THREAD

**Issue by HWR-llc** [HWR-llc/ett#105]
Some examples that are directly integrated into highcharts, but may not be immediately obvious for integrating into vue 2 highcharts

[Zoomable](https://www.highcharts.com/demo/highcharts/line-time-series)

Still looking for others, but this may be best

**Comment by jcjucelyn** [comment]
![image](https://github.com/user-attachments/assets/58fb6623-13d8-418a-9615-24ad54561934)
Resolved! Removed the sliders and integrated data filtering directly into the water quality and habitat (except for diadromous fish) graphs. Pushed to train.
