### ISSUE TITLE
Drop Header for Water Quality Graph and Add Embayment Name to Graph

### ISSUE THREAD

**Issue by HWR-llc** [HWR-llc/ett#106]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/cdd349f4-b657-4e0c-87c4-22984d73327c">

**Comment by jcjucelyn** [comment]
![image](https://github.com/user-attachments/assets/e00e37b3-1084-48c0-8c0c-42ec946e3f13)
Updated graph to remove header and add embayment to the title
