### ISSUE TITLE
Habitat graph "2050 Goal" label is cut off

### ISSUE THREAD

**Issue by rhartzel** [HWR-llc/ett#84]
Minor graph format issue noticed by Pam...the "2050 Goal" label is being cut off (Rockport Harbor, Tidal Flats).  I think this is because the y-axis max is close to the value shown in the graph

![image](https://user-images.githubusercontent.com/101900552/175942710-66c93aad-c186-4b89-bc0d-7f8c75d87f28.png)

**Comment by HWR-llc** [comment]
addressed with #86
