### ISSUE TITLE
Diadromous Fish - Colors

### ISSUE THREAD

**Issue by jcjucelyn** [HWR-llc/ett#88]
Change the colors of the diadromous fish layer-- green for "accessible" and red for "not accessible"

**Comment by HWR-llc** [comment]
This might belong in a different issue, but we should put the accessible value at the bottom of the stacked bar chart.
![image](https://github.com/user-attachments/assets/ab4a0796-733d-4def-95c5-1dd8d1f1cd7e)

My rationale is that once we add the goal for each river, the distance between current and goal will be easy to visualize.

**Comment by jcjucelyn** [comment]
Moved accessible to the bottom of the stack. Fixed colors.
