### ISSUE TITLE
Water Quality Graph Dynamic Filtering

### ISSUE THREAD

**Issue by jcjucelyn** [HWR-llc/ett#95]
Enable filtering for the water graphs in the pop-ups, particularly filtering by date range.
- filter by date range https://www.highcharts.com/docs/stock/range-selector
- add date range filter https://stackoverflow.com/questions/22971239/adding-date-range-filter-to-highcharts-chart
- filter data https://stackoverflow.com/questions/47354334/dynamically-filter-an-array-of-objects-in-vue-js

**Comment by HWR-llc** [comment]
Suggested Change:
Remove sliders and print options from `components/subs/WaterQualityGraph.vue` and create a new component `component/subs/WaterQualityGraphDynamic.vue/` that loads when the enlarge button is clicked:
<img width="308" alt="image" src="https://github.com/user-attachments/assets/2d6d723c-580d-4448-975b-e3b6202cdaf4">

The dynamic graph will include the enhanced functionality (i.e., printing and filtering).

**Comment by jcjucelyn** [comment]
Resolved: suggested change, new component saved as WaterQualityGraphLarge.vue with abilities to print and filter.
